tutu/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets do
    post :buy, on: :member
  end  
  
  namespace :admin do
    resources :railway_stations do 
      patch :update_position, on: :member
      patch :arrival_time, on: :member
      patch :departure_time, on: :member
    end
      
    resources :trains do
      resources :vagons, shallow: true
    end

    resources :routes
    resources :tickets 
  end

  resource :search, only: [:new, :show, :create, :edit]
     
  get 'welcome/index'

  root 'searches#show'

end

tutu/app/models/vagon.rb
class Vagon < ActiveRecord::Base
  self.inheritance_column = :_type_disabled

  belongs_to :train

  validates :number, :side_top_seats, :side_bottom_seats, presence: true
  validates :number, uniqueness: { scope: :train_id}

  before_validation :number_vagon

  scope :economy, -> { where(type: 'EconomyVagon') }
  scope :coupe, -> { where(type: 'CoupeVagon') }
  scope :sitting, -> { where(type: 'SitingVagon') }
  scope :bottom, -> { where(type: 'BottomVagon') }
  
  scope :ordered, -> { order(:number)}
  
  def types 
    types = ['Economy', 'Coupe', 'Sitting', 'Bottom']
  end  

  private

  def number_vagon
    maximum_number = train.vagons.maximum(:number) || 0
    self.number = maximum_number + 1
  end  

end   

tutu/app/controllers/admin/vagons_controller.rb
class Admin::VagonsController < Admin::BaseController
  before_action :set_vagon, only: [:show, :edit, :update, :destroy]
  before_action :set_train, only: [:edit, :update, :create, :new]
  def index
    @vagons = Vagon.all
  end 

  def show
  end 

  def new 
    @vagon = Vagon.new
  end

  def create
    #class_vagon = "#{vagon_params[:type]}" + "Vagon" 
    #@vagon = class_vagon.classify.constantize.new(vagon_params)
    @vagon = @train.vagons.new(vagon_params)    
    if @vagon.save
      redirect_to @train
    else
      render :new 
    end
  end 

  def edit
  end

  def update
    if @vagon.update(vagon_params)
      redirect_to @vagon
    else
      render :edit
    end
  end 

  def destroy
    @vagon.destroy
    redirect_to vagon_path
  end 
    
  private

  def set_vagon
    @vagon = Vagon.find(params[:id])
  end 

  def vagon_params
    params.require(:vagon).permit(:number, :type, :place_down, :place_up, :train_id, :side_top_seats, :side_bottom_seats, :seats)
  end 

  def set_train 
    @train = Train.find(params[:train_id])
  end  
end 

tutu/app/views/admin/vagons/_form.html.erb
<%= form_for [:admin, @train, @vagon] do |f| %>
  <%= render 'common/errors', resource: @train %>
  
  <div class="field">
    <%= f.label :number , "Number of carriage" %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :place_down , "Place down"%>
    <%= f.text_field :place_down %>
  </div>

  <div class="field">
    <%= f.label :place_up , "Place up"%>
    <%= f.text_field :place_up %>
  </div>

  <div class="field">
    <%= f.label :side_top_seats , "Place side top"%>
    <%= f.text_field :side_top_seats %>
  </div>

  <div class="field">
    <%= f.label :side_bottom_seats , "Place side bottom"%>
    <%= f.text_field :side_bottom_seats %>
  </div>

  <div class="field">
    <%= f.label :train, "Train for this carriage" %>
    <%= f.collection_select :train_id, Train.all, :id, :number %>
  </div>


  <div class="field">
    <%= f.label :type, "Type for this carriage" %>
    <%= f.select :type, vagon.types %>
  </div>
  
  <div class="actions">
    <%= f.submit "#{@vagon.new_record? ? 'Create' : 'Change' }"%>
  </div>
<% end %>

tutu/app/views/admin/vagons/edit.html.erb
<h1>Edit Vagon</h1>


<%= render 'form', vagon: @vagon %>

<%= link_to 'Back', admin_vagons_path %>

tutu/app/views/admin/vagons/index.html.erb
<h1>Vagon</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vagons.each do |vagon| %>
      <tr>
        <td><%= vagon.number %></td>
        <td><%= link_to 'Show', admin_vagon_path(vagon) %></td>
        <td><%= link_to 'Edit', edit_admin_vagon_path(vagon) %></td>
        <td><%= link_to 'Destroy', admin_vagon_path(vagon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vagon', new_admin_vagon_path %>

tutu/app/views/admin/vagons/new.html.erb
<h1>New Vagon</h1>

<%= render 'form', vagon: @vagon %>

<%= link_to 'Back', @vagon.train %>

tutu/app/views/admin/vagons/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @vagon.number %>
</p>

<p>
  <strong>Place down:</strong>
  <%= @vagon.place_down %>
</p>

<p>
  <strong>Place down:</strong>
  <%= @vagon.place_up %>
</p>

<p>
  <strong>Place side top:</strong>
  <%= @vagon.side_top_seats %>
</p>

<p>
  <strong>Place side bottom:</strong>
  <%= @vagon.side_bottom_seats %>
</p>

<%= link_to 'Edit', edit_admin_vagon_path(@vagon) %> |
<%= link_to 'Back', admin_vagon_path %>