tutu/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets do
    post :buy, on: :member
  end  
  
  namespace :admin do
    resources :railway_stations do 
      patch :update_position, on: :member
      patch :arrival_time, on: :member
      patch :departure_time, on: :member
    end
      
    resources :trains do
      resources :vagons, shallow: true
    end

    resources :routes
    resources :tickets 
  end

  resource :search, only: [:new, :show, :create, :edit]
     
  get 'welcome/index'

  root 'searches#show'

end

tutu/app/models/train.rb
class Train < ActiveRecord::Base
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :vagons

  validates :number, presence: true

  def count_vagon(type_vagon)
    Vagon.where(type: type_vagon).count  
  end

  def count_place(type_vagon,type_place)
    Vagon.where(type: type_vagon).sum(type_place)
  end  

  def order_vagon
    if order 
      vagons.ordered.reverse
    else
      vagons.ordered
    end
  end  
end

tutu/app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :current_station_id, :route_id)
    end
end

tutu/app/helpers/trains_helper.rb
module TrainsHelper
end

tutu/app/views/admin/trains/_form.html.erb
<%= form_for[:admin, train] do |f| %>
  <%= render 'common/errors', resource: @train %>
  
  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :current_station, "Current station" %>
    <%= f.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>
  
  <div class="field">
    <%= f.label :route, "Route" %>
    <%= f.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit "#{@train.new_record? ? 'Create' : 'Change' }"%>
  </div>
<% end %>

tutu/app/views/admin/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', admin_train_path(train) %></td>
  <td><%= link_to 'Edit', edit_admin_train_path(train) %></td>
  <td><%= link_to 'Destroy', admin_train_path(train), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>s

tutu/app/views/admin/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', [:admin, @train] %> |
<%= link_to 'Back', admin_trains_path %>

tutu/app/views/admin/trains/index.html.erb
<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_admin_train_path %>

tutu/app/views/admin/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', admin_trains_path %>

tutu/app/views/admin/trains/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>
<p>
  <strong>On the station:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Don't have the station
  <% end %>
</p>

<p>
  <% if @train.vagons.empty? %>
    No garriage
  <% else %>
     <% @train.vagons.each do |vagon| %>
      Count <%= "#{vagon.type}" %> vagons:
    <%= @train.count_vagon(vagon.type) %> <br>
     <% end %> 
  <% end %> 

<p>
  <strong>Carriage</strong>
  <ul>
    <% @train.order_vagon.each do |vagon| %>
      <li><%= link_to "Vagon #{vagon.number}", vagon %></li>
    <% end %>   
  </ul>  
</p>

<p>
  <%= link_to "Add vagon", new_admin_train_vagon_path(@train) %>
</p>



<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>