tutu/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets do
    post :buy, on: :member
  end  
  
  namespace :admin do
    resources :railway_stations do 
      patch :update_position, on: :member
      patch :arrival_time, on: :member
      patch :departure_time, on: :member
    end
      
    resources :trains do
      resources :vagons, shallow: true
    end

    resources :routes
    resources :tickets 
  end

  resource :search, only: [:new, :show, :create, :edit]
     
  get 'welcome/index'

  root 'searches#show'

end

tutu/app/models/railway_station.rb
class RailwayStation < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
  has_many :trains, class_name: 'Train', foreign_key: :current_station_id

  validates :title, presence: true  

  scope :ordered, -> { select('railway_stations.*, railway_stations_routes.position').joins(:railway_stations_routes).order("railway_stations_routes.position").uniq }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def arrival_time(route, arrival_time)
    station_route = station_route(route)
    station_route.update(arrival_time: arrival_time) if station_route
  end

  def arrival_in(route)
    station_route(route).try(:arrival_time)
  end

  def departure_time(route, departure_time)
    station_route = station_route(route)
    station_route.update(departure_time: departure_time) if station_route
  end

  def departure_in(route)
    station_route(route).try(:departure_time)
  end

  protected

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

tutu/app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :update_position, :arrival_time, :departure_time]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to [:admin, @railway_station], notice: 'Railway station was successfully created.' 
    else
      render :new 
    end
  end
  
  def update
      if @railway_station.update(railway_station_params)
        redirect_to admin_railway_station_path, notice: 'Railway station was successfully updated.' 
      else
        render :edit 
      end
  end

  def destroy
    @railway_station.destroy
    redirect_to admin_railway_station_path, notice: 'Railway station was successfully destroyed.'
  end

  def update_position
    @route = Route.find(params[:route_id])
    @railway_station.update_position(@route, params[:position])
    redirect_to @route
  end  

  def arrival_time
    @route = Route.find(params[:route_id])
    @railway_station.arrival_time(@route, params[:arrival_time])
    redirect_to @route
  end

  def departure_time
    @route = Route.find(params[:route_id])
    @railway_station.departure_time(@route, params[:departure_time])
    redirect_to @route
  end

  private

    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

tutu/app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

tutu/app/views/admin/railway_stations/_form.html.erb
<%= form_for [:admin, railway_station] do |f| %>

  <%= render 'common/errors', resource: @railway_station %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit', action: railway_station.new_record? ? 'Создать' : 'Изменить') %>
  </div>
<% end %>

tutu/app/views/admin/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', admin_railway_stations_path(@railway_station) %> |
<%= link_to 'Back', admin_railway_stations_path %>

tutu/app/views/admin/railway_stations/index.html.erb
<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railway_stations.each do |railway_station| %>
      <tr>
        <td><%= railway_station.title %></td>
        <td><%= link_to 'Show', admin_railway_station_path(railway_station) %></td>
        <td><%= link_to 'Edit', edit_admin_railway_station_path(railway_station) %></td>
        <td><%= link_to 'Destroy', [:admin, railway_station], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway Station', new_admin_railway_station_path %>

tutu/app/views/admin/railway_stations/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to t('common.back'), admin_railway_stations_path %>

tutu/app/views/admin/railway_stations/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<% if @railway_station.routes.empty? %>
  <p> The station is not on the routes </p>
<% else %>  
  <p>The station is on the next routes:</p>
  <ul>
    <% @railway_station.routes.each do |route| %>
      <li><%= route.name %></li>
    <% end %>
  </ul>
<% end %>      


<%= link_to 'Edit', edit_admin_railway_station_path(@railway_station) %> |
<%= link_to 'Back', admin_railway_stations_path %>