tutu/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets do
    post :buy, on: :member
  end  
  
  namespace :admin do
    resources :railway_stations do 
      patch :update_position, on: :member
      patch :arrival_time, on: :member
      patch :departure_time, on: :member
    end
      
    resources :trains do
      resources :vagons, shallow: true
    end

    resources :routes
    resources :tickets 
  end

  resource :search, only: [:new, :show, :create, :edit]
     
  get 'welcome/index'

  root 'searches#show'

end

tutu/app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true 
  validate :station_count 

  before_validation :set_name
  before_create :station_number

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end  

  def station_count
    if railway_stations.size < 2
      errors.add(:base, "Route should contain at least 2 station")
    end  
  end  

  def station_number
    railway_stations_routes.each_with_index do | item, number |
      item.number = number
    end  
  end 
end

tutu/app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
	before_action :set_route, only: [:show, :edit, :update, :destroy]
	def index
		@routes = Route.all
	end	

	def show
	end	

	def new 
		@route = Route.new
	end

	def create
		@route = Route.new(route_params)
    if @route.save
      redirect_to @route
    else
      render :new 
    end
  end	

  def edit
  end

  def update
  	if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end	

  def destroy
  	@route.destroy
  	redirect_to routes_path
  end	
  	
  private

  def set_route
  	@route = Route.find(params[:id])
  end	

  def route_params
  	params.require(:route).permit(:name, railway_station_ids: [])
  end	
end	

tutu/app/views/admin/routes/_form.html.erb
<%= form_for[:admin, route] do |f| %>
  <%= render 'common/errors', resource: @route %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :railway_station_ids, "Current station" %>
    <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title , {} , { multiple: true }%>
  </div>
  <div class="actions">
    <%= f.submit "#{@route.new_record? ? 'Create' : 'Change' }"%>
  </div>
<% end %>

tutu/app/views/admin/routes/edit.html.erb
<h1>Edit Route</h1>


<%= render 'form', route: @route %>

<%= link_to 'Back', admin_routes_path %>

tutu/app/views/admin/routes/index.html.erb
<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= link_to 'Show', admin_route_path(route) %></td>
        <td><%= link_to 'Edit', edit_admin_route_path(route) %></td>
        <td><%= link_to 'Destroy', admin_route_path(route), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_admin_route_path %>

tutu/app/views/admin/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', admin_routes_path %>

tutu/app/views/admin/routes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>
<p>
  Stations on the route:
</p>
<p>
  <% if @route.railway_stations.empty? %>
    No station
  <% else %>
    <ul>
      <% @route.railway_stations.ordered.each do |station| %>
        <li><%= station.title %></li>
      <% end %>  
    </ul>
  <% end %>
</p>


<!-- <p> 
  Trains on the route:
</p>
<p>
  <% if @route.trains.empty? %>
    No trains on the route
  <% else %>
    <ul>
      <% @route.trains.each do |train| %>
        <li><%= train.number %></li>
      <% end %>  
    </ul>
  <% end %>
</p> -->

<p>
  <strong>Station:</strong>
  <% if @route.railway_stations.empty? %>
      No station
  <% else %>
    <table>
      <thead>
      <tr>
        <td width="100px">Name</td>
        <td>Position</td>
        <td>Arrival time</td>
        <td>Departure time</td>
      </tr>
      </thead>
      <tbody>
      <% @route.railway_stations.ordered.each do |station| %>
          <tr>
            <td><%= station.title %></td>
            <td>
              <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
                <%= number_field_tag :position, station.position_in(@route) %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Change" %>
              <% end %>
            </td>
            <td>
              <%= form_tag arrival_time_admin_railway_station_path(station), method: :patch do %>
                <%= text_field_tag :arrival_time, station.arrival_in(@route) %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Change" %>
              <% end %>
            </td>
            <td>
              <%= form_tag departure_time_admin_railway_station_path(station), method: :patch do %>
                <%= text_field_tag :departure_time, station.departure_in(@route) %>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Change" %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
</p>


<%= link_to 'Edit', edit_admin_route_path(@route) %> |
<%= link_to 'Back', admin_routes_path %>